# Generated by Django 5.1.6 on 2025-02-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='adress',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
